# Name of your application. Used to uniquely configure containers.
service: daisy_on_rails

# Name of the container image.
image: adrienpoly/daisy_on_rails

# Deploy to these servers.
servers:
  web:
    hosts:
      - 1.1.1.1

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: adrienpoly

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    RUBY_YJIT_ENABLE: 1
  secret:
    - RAILS_MASTER_KEY
# Use a different ssh user than root
ssh:
  user: root
# Configure builder setup.
# builder:
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1
volumes:
  - "storage:/rails/storage"
# Use accessory services (secrets come from .env).
accessories:
  # files:
  #   - config/mysql/production.cnf:/etc/mysql/my.cnf
  #   - db/production.sql.erb:/docker-entrypoint-initdb.d/setup.sql
  # directories:
  #   - data:/var/lib/mysql
#   redis:
#     image: redis:7.0
#     host: 192.168.0.2
#     port: 6379
#     directories:
#       - data:/data

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json
# labels:
#   traefik.tcp.routers.other.rule: "HostSNI(`*`)"
#   traefik.tcp.routers.other.entrypoints: search
#   traefik.tcp.services.other.loadbalancer.server.port: 7700
# traefik:
#   options:
#     publish:
#       - 80:80
#       - "7700:7700

